# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build only"
  lane :build_only do
    build_app(
      scheme: "TodoDaily"    # ← スキーム名はご自身のものに合わせてください
    )
  end

  desc "Run unit tests"
  lane :test do
    scan(
      scheme: "TodoDaily",    # ← Xcodeで使っているスキーム名に合わせる
      clean: true
    )
  end
end
