name: iOS Build & Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # 必要な場合、Xcodeバージョン指定（省略可）
      # - name: Select Xcode Version
      #  run: sudo xcode-select -s /Applications/Xcode_16.2.app

      # fastlaneインストール
      - name: Install fastlane
        run: sudo gem install fastlane

      # ビルドのみ実行
      - name: Build only
        run: fastlane build_only
